BucolicSucculent/BucolicSucculent

bower.json
client/index.html

Add jQuery and Bootstrap library and updated index.html

Add jQuery and Bootstrap library and updated index.html

---

API_DEFINITION.md

Add api definitions (draft)
Look at this file to see inputs and outputs of the api
This is just a definitions thing
n/a
Backend API definition
n/a
n/a

Adjusted Params

---

client/app/app.js
client/app/services.js
client/controllers/auth.js
client/controllers/createGame.js
client/controllers/game.js
client/views/createGame.html
client/views/game.html
client/views/game.map.html
server/config/jwt.js
server/config/router.js
server/config/utils.js

This PR integrates authorization into the client and server side. It also gets rid of some vestigial code left over from the initial build and comments out the rest for easy documentation later on.
app.js line 85 - this is where the domain is defined. It should be set to local host. The other IP is for deployment.
Start mysql and server.js and take the app for a spin. After logging in, go to your application tab in dev tools and delete the JWT from local storage. Then test again. Ensure rerouting occurs from client side and the server will deny login for a wrong username/pw combo.
I stole some code from the shortly-angular sprint... specifically lines 64 through to the end of app.js. Interestingly, I didn't run into any CORS issues while troubleshooting.

Integrate Auth functionality

---

client/app/app.js
client/app/services.js
client/controllers/auth.js
client/index.html
client/styles/styles.css
client/views/login.html
client/views/signup.html
server/config/jwt.js
server/config/router.js

adds redirect after login, removes interceptor added in last checkin, also sets default host to 127.0.0.1
charges are in 3 files:
client/app/app.js - commented out said interceptor, can be removed
client/app/services.js - removed console.logs
client/controllers/auth.js - add token to http common headers and do redirect for login
by login in or signinup

Add redirect after login, removes interceptor, set default host to localhost

---

client/app/services.js

Fixes the bug where requests don't attach the token
Changes in services.js
Make a user, create a game and click the link. Then hit refresh, you should still be authed and it should still reload the game

Makes sure it uses the token before each request

---

server/config/db-config.js
server/config/router.js
server/games/games.js

Refactor the router code for the game creation. Location creation is now async and now Sequelize will handle the Game and Creator (User) association, the pathUrl is now shortened, and the outdated comments are removed.
Start in the db-config.js and game.js to verify the Sequelize definition. Then in /api/game/create endpoint the router.js. 
Drop the database bc the Sequelize definitions has changed. Create a game and verify in tables that game/location/user/usergame associations are created properly with the new shortened pathUrl

Router code clean up - Game Creation/pathUrl shortened

---

package.json
server/config/router.js

Refactoring of the returnStatuses function to better utilize Sequelize's library and their Promises.
I also cleaned up the response data to the client app. (example data structure is included as a comment in the code).
start at the returnStatuses function in server/config/router.js
if the auth middleware is disabled (see code comments), the function and the results can be tested using postman.
If the auth middleware is enabled (as if in production), the functionality can be verified by using the website (creating new game, joining a game, changing a status, and verifying the status is retained to the correct user)
Sequelize is horrible. But the beast is tamed.
Is Sequelize God punishing me?

More router.js Cleanup - Refactor returnStatuses (and code clean-up)

---

client/app/app.js

Fix the bug where it doesn't redirect to login due to resolve's getData failing
app.js
Create a game. Get another device that's not logged in to join that game. It should now redirect to login as expected

Fix fetching data only when logged in

---

client/controllers/auth.js
client/controllers/game.js

Saves the game id from game and redirects you to it after signup or login
auth.js and game.js
Create a game. Have a device that's not logged in use the link. After logging in/signing up it should redirect to the game

Added redirect after login.

---

server/config/router.js

During GET requests to the /api/game/ endpoint with only a Username parameter, it will now include a createdAt for when each User joined the game.
router.js on line 281
if auth middleware is disabled, you can use postman to confirm data structure
additional data for client-side

Return a createdAt for when each User joined the game.

---

UserGuide.md

Add a rough draft of user guide.
userguide.md

Added user guide

---

client/app/app.js
client/controllers/auth.js
client/controllers/game.js
server/config/db-config.js
server/config/jwt.js
server/config/router.js
server/config/utils.js
server/server.js
specs/server/ServerSpec.js

create another test case for Game Creation.
Also lots of code cleanup regarding console.logs
start in the specs/server/server.js
make sure to drop your current database because the sequelize definitions were modified and need to be updated.
proper removal of data from the database and also more tests!

More test cases

---

client/index.html

collapses navbar  and hides logo when screen size is small
index.html

Add responsive functionality to navbar

---

.travis.yml

Add travis file to begin CI on our project.

Add travis file.

---

docs/client.md
docs/deployment.md

Add documentation
docs/client.md
docs/deployment.md

Adde client and deployment documentation

---

.travis.yml
server/config/db-config.js
server/config/helpers.js
server/config/jwt.js
server/config/router.js
server/config/utils.js
server/server.js
settings.json

Move config to seperate file and moved appropriate jwt functions to jwt.js

Cleanup Jwt

---

docs/tests.md
specs/server/ServerSpec.js

add documentation about tests and clean up styles on ServerSpec.js

Documentation

---

API_DEFINITION.md
docs/agile.md

Adds Agile process documentation to repository
docs/Agile.md
N/A - got to live it
in list Sprint 4 9/9-9/12
Members
BK/CM/DL/SC

Agile process documentation: add to repository

---

docs/agile.md

Expand on the Retrospective portion

more agile explication

---

_CONTRIBUTING.md
_STYLE-GUIDE.md
client/app/app.js
client/app/services.js
client/controllers/auth.js
client/controllers/createGame.js
client/controllers/dashboard.js
client/controllers/game.js
server/config/helpers.js
server/config/jwt.js
server/config/router.js
server/config/utils.js

Add style guide and combed through all of the code to fix styling errors.

Inlcude Style Guide and fix styling throughout project.

---

docs/API_DEFINITION.md
docs/PULL_REQUEST_TEMPLATE
docs/UserGuide.md
docs/dbSchemaPlan.md
docs/server.md

add to server Docs, move docs into doc directory

server doc additions

---

.jshintrc
client/app/app.js
client/controllers/createGame.js
client/controllers/game.js
docs/API_DEFINITION.md
docs/PULL_REQUEST_TEMPLATE
docs/server.md

add a lint config file for jshint and fixed client files to match styling guide.

Styleguide

---

server/config/router.js
server/server.js

Change port to 80 when in production environment

Change port to 80 for production env

---

client/controllers/auth.js

Gracefully handle errors on login and signup

Handle login and signup errors

---

docs/tests.md

Update test documentation to include TravisCI

Added statement about TravisCI

---

client/views/createGame.html

Prevent user from creating game with no markers

Prevent user from creating game with no markers

---

client/index.html
client/styles/styles.css

Change styles
